"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loyiha ildizidagi .env (bot bilan bir xil) — Uysot tokeni shu yerda
load_dotenv(BASE_DIR.parent / ".env")

# --- Uysot showroom API (sync_layouts buyrug'i uchun) ---
UYSOT_SHOWROOM_BASE = os.getenv(
    "UYSOT_SHOWROOM_BASE", "https://srv.showroom.app.uysot.uz/v1/website")
UYSOT_SHOWROOM_TOKEN = os.getenv("UYSOT_SHOWROOM_TOKEN", "")
UYSOT_HOUSE_ID = os.getenv("UYSOT_HOUSE_ID", "880")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Ishlab chiqarishda .env da DJANGO_SECRET_KEY ni to'ldiring.
# Pastdagi qiymat FAQAT lokal ishlab chiqish uchun (repo public — haqiqiy kalit emas).
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only-insecure-key-set-DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

# Lokal + kelajakdagi host uchun. Ishlab chiqarishda aniq domenlarga cheklang
# (.env: DJANGO_ALLOWED_HOSTS=bot.example.uz,127.0.0.1).
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0").split(",")

# Bot API himoyasi (inventory/auth.py). Bo'sh = himoya o'chiq (faqat lokal!).
BOT_API_TOKEN = os.getenv("BOT_API_TOKEN", "")

# Tashqi (public) bazaviy URL — bot rasm URL'larini shu domen bilan oladi
# (bot va backend boshqa-boshqa mashinada bo'lsa majburiy). Masalan:
# PUBLIC_BASE_URL=https://admin.nurlidiyor.uz  Bo'sh bo'lsa so'rov hostidan olinadi.
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").rstrip("/")

# --- Production himoya tekshiruvlari (DEBUG o'chiq bo'lsa MAJBURIY) ---
if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured
    if SECRET_KEY == "dev-only-insecure-key-set-DJANGO_SECRET_KEY":
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY .env da yo'q — production'da default kalit bilan "
            "ishga tushirish TAQIQLANADI.")
    if not BOT_API_TOKEN:
        raise ImproperlyConfigured(
            "BOT_API_TOKEN .env da yo'q — production'da API himoyasiz qolmasin.")
    # Xavfsizlik sarlavhalari
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SESSION_COOKIE_HTTPONLY = True
    # HTTPS ortida bo'lsa yoqing (nginx TLS bilan):
    if os.getenv("DJANGO_HTTPS", "0") == "1":
        CSRF_COOKIE_SECURE = True
        SESSION_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True   # admin.* alohida domen — xavfsiz
        SECURE_HSTS_PRELOAD = True
        SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',
    'kb',        # bot bilim bazasi (storage/knowledge.db) — admin orqali ko'rish/tahrirlash
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: static fayllarni DEBUG=False da ham Django o'zi uzatadi
    # (SecurityMiddleware'dan KEYIN, qolganidan OLDIN turishi kerak)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # admin dashboard (templates/admin/index.html)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # Bot bilim bazasi (RAG): hujjatlar, bo'laklar, faktlar, lidlar, suhbatlar.
    # Bu faylni bot o'zi yaratadi/yozadi (knowledge/db.py) — Django faqat ulanadi,
    # migratsiya qilmaydi (kb/router.py). Bot WAL rejimida yozadi, shuning uchun
    # bir vaqtda o'qish/yozish xavfsiz; timeout - qulf kutish muddati.
    'knowledge': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.parent / 'storage' / 'knowledge.db',
        'OPTIONS': {'timeout': 30},
    },
}

# kb app modellarini 'knowledge' bazasiga yo'naltiradi
DATABASE_ROUTERS = ['kb.router.KnowledgeRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'   # collectstatic shu yerga yig'adi
STATIC_ROOT.mkdir(exist_ok=True)         # WhiteNoise "papka yo'q" ogohlantirmasin

# WhiteNoise: siqilgan/keshlanadigan static (DEBUG=False da ham ishlaydi)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Media (yuklangan planirovka rasmlari)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
