# Generated by Django 5.2.16 on 2026-07-17 14:37

import kb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField(verbose_name='Tartib raqami')),
                ('page', models.IntegerField(blank=True, null=True, verbose_name='Sahifa')),
                ('text', models.TextField(verbose_name='Matn')),
            ],
            options={
                'verbose_name': "Bo'lak (chunk)",
                'verbose_name_plural': "Bo'laklar (chunks)",
                'db_table': 'chunks',
                'ordering': ['document_id', 'chunk_index'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField(verbose_name='Fayl nomi')),
                ('source_type', models.TextField(default='pdf', help_text='pdf | text | manual', verbose_name='Manba turi')),
                ('title', models.TextField(blank=True, help_text='Claude bergan sarlavha/xulosa', null=True, verbose_name='Sarlavha')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Qisqa mazmun')),
                ('num_pages', models.IntegerField(blank=True, null=True, verbose_name='Sahifalar')),
                ('num_chunks', models.IntegerField(blank=True, default=0, null=True, verbose_name="Bo'laklar")),
                ('file_hash', models.TextField(blank=True, help_text='Takror yuklashni oldini oladi', null=True, unique=True, verbose_name='Fayl hash')),
                ('created_at', models.TextField(default=kb.models._now, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'db_table': 'documents',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, help_text='narx | qurilish | joylashuv | shartlar | umumiy ...', null=True, verbose_name='Kategoriya')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Tipik savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('created_at', models.TextField(default=kb.models._now, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Fakt',
                'verbose_name_plural': 'Faktlar',
                'db_table': 'facts',
                'ordering': ['category', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Ismi')),
                ('username', models.TextField(blank=True, null=True, verbose_name='Username')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Telefon')),
                ('first_seen', models.TextField(default=kb.models._now, verbose_name='Birinchi murojaat')),
                ('last_seen', models.TextField(default=kb.models._now, verbose_name='Oxirgi murojaat')),
                ('num_messages', models.IntegerField(blank=True, default=0, null=True, verbose_name='Xabarlar soni')),
            ],
            options={
                'verbose_name': 'Lid (mijoz)',
                'verbose_name_plural': 'Lidlar (mijozlar)',
                'db_table': 'leads',
                'ordering': ['-last_seen'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.IntegerField(verbose_name='Telegram ID')),
                ('role', models.TextField(choices=[('user', 'Mijoz'), ('assistant', 'Bot')], verbose_name='Kim yozgan')),
                ('content', models.TextField(verbose_name='Matn')),
                ('created_at', models.TextField(default=kb.models._now, verbose_name='Vaqt')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar (suhbat tarixi)',
                'db_table': 'messages',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, verbose_name='Nomi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='Xonalar')),
                ('area_m2', models.FloatField(blank=True, null=True, verbose_name='Maydoni (m²)')),
                ('floor', models.TextField(blank=True, null=True, verbose_name='Qavat')),
                ('price', models.TextField(blank=True, null=True, verbose_name='Narx')),
                ('build_stage', models.TextField(blank=True, null=True, verbose_name='Qurilish bosqichi')),
                ('status', models.TextField(blank=True, help_text='sotuvda | band | sotilgan', null=True, verbose_name='Holati')),
                ('extra', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha")),
                ('created_at', models.TextField(default=kb.models._now, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': "Uy / ob'ekt",
                'verbose_name_plural': "Uylar / ob'ektlar",
                'db_table': 'properties',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
    ]
