# Generated by Django 5.2.16 on 2026-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(verbose_name='Xona soni')),
                ('area', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Maydon (m²)')),
                ('blocks', models.CharField(blank=True, help_text='Masalan: 3, 4, 5', max_length=100, verbose_name='Bloklar')),
                ('available_count', models.IntegerField(default=0, verbose_name='Sotuvda (qolgan)')),
                ('total_count', models.IntegerField(default=0, verbose_name='Jami (sotilgan bilan)')),
                ('sample_flat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Namuna flat ID')),
                ('min_floor', models.IntegerField(blank=True, null=True, verbose_name='Eng past qavat')),
                ('max_floor', models.IntegerField(blank=True, null=True, verbose_name='Eng baland qavat')),
                ('planirovka', models.ImageField(blank=True, null=True, upload_to='planirovka/', verbose_name='Planirovka rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name="Botда ko'rsatilsinmi")),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sync')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xonadon turi',
                'verbose_name_plural': 'Xonadon turlari',
                'ordering': ('rooms', 'area'),
                'unique_together': {('rooms', 'area')},
            },
        ),
    ]
