# Generated by Django 5.2.16 on 2026-07-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='planirovka_3d',
            field=models.ImageField(blank=True, null=True, upload_to='planirovka_3d/', verbose_name='Planirovka rasmi (3D)'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='planirovka',
            field=models.ImageField(blank=True, null=True, upload_to='planirovka/', verbose_name='Planirovka rasmi (2D)'),
        ),
    ]
