# Generated by Django 5.2.16 on 2026-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_layout_planirovka_3d_alter_layout_planirovka'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('content', models.TextField(help_text="Bot shu matnni o'qiydi. Fakt qo'shish/o'zgartirish shu yerda.", verbose_name='Matn (markdown)')),
                ('order', models.IntegerField(default=0, help_text='Kichik raqam birinchi keladi', verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Botga berilsinmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi tahrir')),
            ],
            options={
                'verbose_name': "Bilim bo'limi",
                'verbose_name_plural': 'Bilim bazasi (bot faktlari)',
                'ordering': ('order', 'id'),
            },
        ),
    ]
