# Generated by Django 5.2.16 on 2026-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_knowledgesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_prepayment_percent', models.DecimalField(decimal_places=1, help_text="Umumiy narxning necha foizi to'lansa shu pog'ona ishlaydi", max_digits=5, verbose_name="Boshlang'ich ulushi kamida (%)")),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chegirma (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Chegirma pog'onasi",
                'verbose_name_plural': "Chegirma zinapoyasi (boshlang'ichga qarab)",
                'ordering': ('min_prepayment_percent',),
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_prepayment', models.DecimalField(decimal_places=0, default=30000000, help_text="Kalkulyatorda boshlang'ich kiritilmasa shu summa olinadi (kompaniya siyosati: har doim 30 mln).", max_digits=15, verbose_name="Standart boshlang'ich to'lov (so'm)")),
                ('repair_price_per_m2', models.DecimalField(decimal_places=0, default=3000000, help_text="Ta'mirli variantda har m² uchun qo'shiladigan summa.", max_digits=12, verbose_name="Ta'mir tarifi (so'm/m²)")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi tahrir')),
            ],
            options={
                'verbose_name': 'Narx sozlamalari',
                'verbose_name_plural': 'Narx sozlamalari',
            },
        ),
    ]
