# Generated by Django 5.2.16 on 2026-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_discounttier_pricingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.TextField(verbose_name='Savol')),
                ('javob', models.TextField(help_text='Bot AYNAN shu javob mazmuni bilan javob beradi.', verbose_name='Rasmiy javob')),
                ('kategoriya', models.CharField(choices=[('asosiy', 'Asosiy'), ('etiroz', "E'tiroz (qarshiliklar)"), ('hudud', 'Hudud'), ('jarayon', 'Jarayon'), ('kompaniya', 'Kompaniya'), ('narx', 'Narx'), ('ochiq', 'Ochiq savollar'), ('qurilish', 'Qurilish'), ('topshirish', 'Topshirish'), ('umumiy', 'Umumiy'), ('xonadon', 'Xonadon')], default='umumiy', max_length=30, verbose_name='Kategoriya')),
                ('sana_sezgir', models.BooleanField(default=False, help_text="Vaqt o'tishi bilan eskiradigan javob (masalan qurilish holati).", verbose_name='Sana-sezgir')),
                ('qayta_tekshirish_kerak', models.BooleanField(default=False, verbose_name='Qayta tekshirish kerak')),
                ('yangilangan', models.DateField(blank=True, null=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Botga berilsinmi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rasmiy savol-javob',
                'verbose_name_plural': 'Rasmiy savol-javoblar (anketa)',
                'ordering': ('kategoriya', 'id'),
                'constraints': [models.UniqueConstraint(fields=('savol', 'javob'), name='uniq_savol_javob')],
            },
        ),
    ]
