# Generated by Django 5.2.16 on 2026-07-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_qaentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='tariff_m2_high_floors',
            field=models.DecimalField(decimal_places=0, default=8490000, max_digits=12, verbose_name="Rasmiy tarif: 6–9-qavat (so'm/m²)"),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='tariff_m2_low_floors',
            field=models.DecimalField(decimal_places=0, default=8990000, max_digits=12, verbose_name="Rasmiy tarif: 1–5-qavat (so'm/m²)"),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='tariff_warning',
            field=models.CharField(blank=True, default='', help_text="Sync Uysot'dagi m² narx bilan farq topsa shu yerga yozadi (dashboard'da qizil ko'rinadi).", max_length=255, verbose_name='Tarif ogohlantirishi'),
        ),
    ]
